[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.2" # replace with the version you're using
tokio = { version = "1", features = ["full"] } # replace with the version you're using